kind: Secret
apiVersion: v1
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  selfLink: /api/v1/namespaces/fhir/secrets/mariadb-xxx
  resourceVersion: '42839766'
  name: mariadb-xxx
  uid: 31db471d-7967-44bc-ae05-c8bf7eebf4d0
  creationTimestamp: '2021-12-21T00:57:08Z'
  managedFields:
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: v1
      time: '2021-12-21T00:57:08Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:database-name': {}
          'f:database-password': {}
          'f:database-root-password': {}
          'f:database-user': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:template.openshift.io/expose-database_name': {}
            'f:template.openshift.io/expose-password': {}
            'f:template.openshift.io/expose-root_password': {}
            'f:template.openshift.io/expose-username': {}
          'f:labels':
            .: {}
            'f:template': {}
            'f:template.openshift.io/template-instance-owner': {}
        'f:type': {}
  namespace: fhir
  labels:
    template: mariadb-ephemeral-template
    template.openshift.io/template-instance-owner: 6a2d7b76-d86b-445d-b1d8-1f29c463e150
data:
  database-name: cWll
  database-password: cWll
  database-root-password: cWll
  database-user: cWll
type: Opaque
