kind: PersistentVolume
apiVersion: v1
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  selfLink: /api/v1/persistentvolumes/mariadb-fhir
  resourceVersion: '49431329'
  name: mariadb-fhir
  uid: a2726e2a-9d43-456f-a526-e38cc5c932f6
  creationTimestamp: '2021-12-20T22:19:42Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2021-12-20T22:20:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
        'f:spec':
          'f:accessModes': {}
          'f:capacity':
            .: {}
            'f:storage': {}
          'f:nfs':
            .: {}
            'f:path': {}
            'f:server': {}
          'f:persistentVolumeReclaimPolicy': {}
          'f:volumeMode': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-01-06T22:22:14Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:pv.kubernetes.io/bound-by-controller': {}
        'f:spec':
          'f:claimRef':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:namespace': {}
            'f:resourceVersion': {}
            'f:uid': {}
        'f:status':
          'f:phase': {}
  finalizers:
    - kubernetes.io/pv-protection
  labels:
    app: mariadb-fhir
spec:
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.22.1
    path: /shares/mariadb-fhir
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: fhir
    name: mariadb-fhir
    uid: 18bc486f-ce46-4594-b191-6c9cd3cd99f8
    apiVersion: v1
    resourceVersion: '49430490'
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
